services:
  postgres-test:
    image: postgres:16
    container_name: mini-crm-postgres-test
    restart: no
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_crm_test
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
